spring:
  application:
    name: deloitte-ai
  datasource:
    url: jdbc:postgresql://postgres:5432/appdb
    username: appuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # or validate / create / none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

application:
  ai:
    api-key: ${OPEN_API_KEY:key}
    model: ${AI_MODEL:gpt-4o-mini}
    temperature: 0.1